-- Auto-generated Neovim color configuration
-- This file is auto-generated by hyprstyle
-- Applies hyprstyle colors to override colorscheme highlights

local M = {}

function M.setup()
  -- Terminal colors (ANSI color codes 0-15)
  -- Used by terminal UI and colorschemes that respect terminal colors
  vim.g.terminal_color_0 = '#000000'
  vim.g.terminal_color_8 = '#0A0B22'
  vim.g.terminal_color_1 = '#f38ba8'
  vim.g.terminal_color_9 = '#f38ba8'
  vim.g.terminal_color_2 = '#a6e3a1'
  vim.g.terminal_color_10 = '#a6e3a1'
  vim.g.terminal_color_3 = '#f9e2af'
  vim.g.terminal_color_11 = '#f9e2af'
  vim.g.terminal_color_4 = '#AABFE1'
  vim.g.terminal_color_12 = '#AABFE1'
  vim.g.terminal_color_5 = '#585EA0'
  vim.g.terminal_color_13 = '#585EA0'
  vim.g.terminal_color_6 = '#AABFE1'
  vim.g.terminal_color_14 = '#AABFE1'
  vim.g.terminal_color_7 = '#AABFE1'
  vim.g.terminal_color_15 = '#AABFE1'

  -- Ensure true color support is enabled
  vim.opt.termguicolors = true

  -- Apply hyprstyle colors to editor highlights
  -- This overrides the colorscheme to use our extracted colors
  local hl = vim.api.nvim_set_hl

  -- Basic UI colors
  hl(0, "Normal", { fg = "#AABFE1", bg = "#0A0B22" })
  hl(0, "NormalNC", { fg = "#AABFE1", bg = "#0A0B22" })
  hl(0, "NormalFloat", { fg = "#AABFE1", bg = "#0A0B22" })

  -- Cursor and selection
  hl(0, "Cursor", { fg = "#0A0B22", bg = "#AABFE1" })
  hl(0, "CursorLine", { bg = "#0f1027" })
  hl(0, "CursorLineNr", { fg = "#AABFE1", bold = true })
  hl(0, "Visual", { fg = "#0A0B22", bg = "#585EA0" })

  -- Line numbers and signs
  hl(0, "LineNr", { fg = "#a0a0a0" })
  hl(0, "SignColumn", { fg = "#a0a0a0", bg = "#0A0B22" })

  -- Syntax highlighting
  hl(0, "Statement", { fg = "#AABFE1", bold = true })
  hl(0, "String", { fg = "#a6e3a1" })
  hl(0, "Comment", { fg = "#a0a0a0", italic = true })
  hl(0, "Type", { fg = "#AABFE1" })
  hl(0, "Function", { fg = "#AABFE1" })
  hl(0, "Keyword", { fg = "#AABFE1", bold = true })
  hl(0, "Constant", { fg = "#585EA0" })

  -- Error, Warning, Info
  hl(0, "Error", { fg = "#f38ba8", bold = true })
  hl(0, "Warning", { fg = "#f9e2af", bold = true })
  hl(0, "DiagnosticError", { fg = "#f38ba8" })
  hl(0, "DiagnosticWarn", { fg = "#f9e2af" })
  hl(0, "DiagnosticInfo", { fg = "#AABFE1" })
  hl(0, "DiagnosticHint", { fg = "#AABFE1" })

  -- Search and diff
  hl(0, "Search", { bg = "#f9e2af" })
  hl(0, "IncSearch", { bg = "#585EA0" })
  hl(0, "DiffAdd", { bg = "#a6e3a1" })
  hl(0, "DiffDelete", { bg = "#f38ba8" })
  hl(0, "DiffChange", { bg = "#AABFE1" })

  -- Menu and completion
  hl(0, "Pmenu", { fg = "#AABFE1", bg = "#a0a0a0" })
  hl(0, "PmenuSel", { fg = "#0A0B22", bg = "#585EA0", bold = true })
  hl(0, "PmenuBorder", { fg = "#585EA0" })
end

return M
