#!/bin/bash
#
# Arch Linux Configuration Backup Script
# Backs up system configuration files and commits to git repository
#

set -e

USER_HOME="$HOME"

BACKUP_DIR="$USER_HOME/Documents/arch-backup"
CONFIG_DIR="$BACKUP_DIR/configs"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Non-interactive mode
NON_INTERACTIVE="${NON_INTERACTIVE:-false}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Initialize git repository if not present
init_git_repo() {
    cd "$BACKUP_DIR"

    if [ ! -d ".git" ]; then
        if [ "$NON_INTERACTIVE" = "true" ]; then
            log_warn "No git repository found and running in non-interactive mode"
            log_warn "Please run backup.sh manually first to set up the repository"
            exit 1
        fi

        log_warn "No git repository found in $BACKUP_DIR"
        read -p "Enter git repository URL to clone (or press Enter to initialize new repo): " repo_url

        if [ -n "$repo_url" ]; then
            # Save current files temporarily
            temp_dir=$(mktemp -d)
            cp -r "$BACKUP_DIR"/* "$temp_dir/" 2>/dev/null || true

            # Clone the repository
            cd "$USER_HOME/Documents"
            rm -rf "$BACKUP_DIR"
            git clone "$repo_url" arch-backup
            cd "$BACKUP_DIR"

            # Restore scripts if they don't exist in cloned repo
            if [ ! -f "backup.sh" ] && [ -f "$temp_dir/backup.sh" ]; then
                cp "$temp_dir/backup.sh" .
            fi
            if [ ! -f "restore.sh" ] && [ -f "$temp_dir/restore.sh" ]; then
                cp "$temp_dir/restore.sh" .
            fi

            rm -rf "$temp_dir"
            log_info "Repository cloned successfully"
        else
            git init
            log_info "Initialized new git repository"
            read -p "Enter remote repository URL (optional, press Enter to skip): " remote_url
            if [ -n "$remote_url" ]; then
                git remote add origin "$remote_url"
                log_info "Added remote origin: $remote_url"
            fi
        fi
    fi
}

# Create directory structure
create_dirs() {
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$BACKUP_DIR/packages"
    mkdir -p "$BACKUP_DIR/scripts"
    mkdir -p "$BACKUP_DIR/local-bin"
}

# Backup function - copies file/directory if it exists
backup_item() {
    local src="$1"
    local dest="$2"

    if [ -e "$src" ]; then
        mkdir -p "$(dirname "$dest")"
        cp -r "$src" "$dest"
        log_info "Backed up: $src"
    else
        log_warn "Not found, skipping: $src"
    fi
}

# Directories and patterns to exclude from backup (sensitive/large/cache data)
EXCLUDE_PATTERNS=(
    # Hyprstyle-generated files (theme configs)
    # These are generated by hyprstyle from https://github.com/sergey-shulyak/hyprstyle
    "hypr/colors.conf"
    "hypr/hyprlock.conf"
    "hypr/hyprpaper.conf"
    "kitty/kitty.conf"
    "mako/config"
    "waybar/style.css"
    "wofi/style.css"
    "nvim/lua/nvim-colors.lua"

    # Sensitive data
    ".gnupg"
    ".ssh/id_*"
    ".ssh/*.pem"
    ".ssh/known_hosts"
    ".ssh/authorized_keys"
    ".pki"
    ".cert"
    ".password-store"

    # Credentials and secrets
    "**/credentials*"
    "**/secrets*"
    "**/.env"
    "**/token*"
    "**/auth*"
    "**/*key*.json"
    "**/*secret*"

    # Cache and temporary files
    ".cache"
    ".local/share/Trash"
    "**/Cache"
    "**/cache"
    "**/CacheStorage"
    "**/*.log"
    "**/logs"
    "**/.npm"
    "**/.cargo/registry"
    "**/.rustup"
    "**/node_modules"
    "**/__pycache__"
    "**/*.pyc"
    "**/venv"
    "**/.venv"

    # Browser data (large and contains sensitive info)
    ".mozilla"
    "google-chrome"
    "google-chrome-beta"
    "google-chrome-unstable"
    "chromium"
    "BraveSoftware"
    "firefox"
    "vivaldi"
    "Microsoft/Edge"

    # Password managers and sensitive apps
    "1Password"
    "Bitwarden"
    "KeePassXC"

    # Application data (large/regenerable)
    ".local/share/Steam"
    ".steam"
    ".wine"
    ".local/share/lutris"
    ".var"
    ".local/share/flatpak"
    "snap"

    # IDE/Editor data and extensions
    ".vscode/extensions"
    ".config/Code/CachedData"
    ".config/Code/CachedExtensions"
    ".config/Code/User/workspaceStorage"
    ".config/Code/logs"
    ".local/share/JetBrains"

    # History files (can contain sensitive commands)
    ".bash_history"
    ".zsh_history"
    ".histfile"
    ".python_history"
    ".lesshst"
    ".wget-hsts"
)

# Build rsync exclude arguments
build_exclude_args() {
    local args=""
    for pattern in "${EXCLUDE_PATTERNS[@]}"; do
        args="$args --exclude=$pattern"
    done
    echo "$args"
}

# Backup entire .config directory
backup_config_dir() {
    log_info "Backing up ~/.config directory..."

    local exclude_args=$(build_exclude_args)

    mkdir -p "$CONFIG_DIR/home/.config"

    # Use rsync with exclusions
    eval rsync -a --delete $exclude_args "$USER_HOME/.config/" "$CONFIG_DIR/home/.config/"

    log_info "Backed up ~/.config"
}

# Backup home directory dotfiles
backup_home_dotfiles() {
    log_info "Backing up home directory dotfiles..."

    # List of dotfiles to backup (files only, not directories)
    local dotfiles=(
        ".bashrc"
        ".bash_profile"
        ".zshrc"
        ".zprofile"
        ".profile"
        ".gitconfig"
        ".gitignore_global"
        ".vimrc"
        ".tmux.conf"
        ".xinitrc"
        ".Xresources"
        ".xprofile"
        ".gtkrc-2.0"
        ".inputrc"
        ".editorconfig"
    )

    for file in "${dotfiles[@]}"; do
        if [ -f "$USER_HOME/$file" ]; then
            backup_item "$USER_HOME/$file" "$CONFIG_DIR/home/$file"
        fi
    done

    # SSH config only (not keys)
    if [ -f "$USER_HOME/.ssh/config" ]; then
        mkdir -p "$CONFIG_DIR/home/.ssh"
        cp "$USER_HOME/.ssh/config" "$CONFIG_DIR/home/.ssh/config"
        log_info "Backed up: $USER_HOME/.ssh/config"
    fi

    # Fish shell data (functions, completions - but not history)
    if [ -d "$USER_HOME/.local/share/fish" ]; then
        mkdir -p "$CONFIG_DIR/home/.local/share"
        rsync -a --exclude='fish_history' "$USER_HOME/.local/share/fish/" "$CONFIG_DIR/home/.local/share/fish/"
        log_info "Backed up: $USER_HOME/.local/share/fish"
    fi
}

# Backup user scripts in ~/.local/bin
backup_local_bin() {
    log_info "Backing up ~/.local/bin directory..."

    if [ -d "$USER_HOME/.local/bin" ]; then
        mkdir -p "$BACKUP_DIR/local-bin"
        cp -r "$USER_HOME/.local/bin"/* "$BACKUP_DIR/local-bin/" 2>/dev/null || true
        log_info "Backed up: $USER_HOME/.local/bin"
    else
        log_warn "Not found, skipping: $USER_HOME/.local/bin"
    fi
}

# Backup configuration files
backup_configs() {
    log_info "Backing up configuration files..."

    backup_config_dir
    backup_home_dotfiles

    # System configs (device-agnostic only)
    log_info "Backing up system configs..."
    if [ -r "/etc/pacman.conf" ]; then
        backup_item "/etc/pacman.conf" "$CONFIG_DIR/etc/pacman.conf"
    fi
    if [ -r "/etc/makepkg.conf" ]; then
        backup_item "/etc/makepkg.conf" "$CONFIG_DIR/etc/makepkg.conf"
    fi
    # Skipped device-specific configs:
    # - /etc/fstab (disk/partition specific)
    # - /etc/hostname (machine specific)
    # - /etc/X11/xorg.conf.d (hardware specific)
    if [ -r "/etc/locale.conf" ]; then
        backup_item "/etc/locale.conf" "$CONFIG_DIR/etc/locale.conf"
    fi
    if [ -r "/etc/vconsole.conf" ]; then
        backup_item "/etc/vconsole.conf" "$CONFIG_DIR/etc/vconsole.conf"
    fi
    if [ -d "/etc/environment.d" ]; then
        backup_item "/etc/environment.d" "$CONFIG_DIR/etc/environment.d"
    fi
    if [ -r "/etc/tlp.conf" ]; then
        backup_item "/etc/tlp.conf" "$CONFIG_DIR/etc/tlp.conf"
    fi
}

# GPU driver packages to exclude from backup/restore
GPU_DRIVERS=(
    "nvidia-open-dkms"
    "nvidia-dkms"
    "nvidia"
    "nvidia-utils"
    "nvidia-settings"
    "libva-nvidia-driver"
    "libxnvctrl"
    "libnvidia-container"
    "libnvidia-container-tools"
    "amd-ucode"
    "intel-ucode"
    "intel-media-driver"
    "libva-intel-driver"
    "libva-mesa-driver"
    "vulkan-intel"
    "vulkan-radeon"
    "vulkan-amd"
    "lib32-vulkan-intel"
    "lib32-vulkan-radeon"
    "lib32-vulkan-amd"
    "mesa"
    "lib32-mesa"
)

# Build grep pattern for GPU drivers
build_gpu_driver_pattern() {
    local pattern="^("
    for driver in "${GPU_DRIVERS[@]}"; do
        pattern="${pattern}${driver}|"
    done
    pattern="${pattern%|})\$"
    echo "$pattern"
}

# Backup package lists
backup_packages() {
    log_info "Backing up package lists..."

    local gpu_pattern=$(build_gpu_driver_pattern)

    # Explicitly installed native packages (from official repos, excluding GPU drivers)
    pacman -Qqen | grep -vE "$gpu_pattern" > "$BACKUP_DIR/packages/pacman.txt"
    log_info "Saved native packages list (GPU drivers excluded)"

    # AUR packages (foreign, excluding GPU drivers)
    pacman -Qqem | grep -vE "$gpu_pattern" > "$BACKUP_DIR/packages/aur.txt"
    log_info "Saved AUR packages list (GPU drivers excluded)"
}


# Show summary of changed files
show_changed_files() {
    cd "$BACKUP_DIR"

    local changed_files=$(git diff --cached --name-only)
    local deleted_files=$(git diff --cached --diff-filter=D --name-only)
    local added_files=$(git diff --cached --diff-filter=A --name-only)
    local modified_files=$(git diff --cached --diff-filter=M --name-only)

    if [ -z "$changed_files" ]; then
        return
    fi

    echo ""
    log_info "Changed files summary:"

    if [ -n "$added_files" ]; then
        echo -e "${GREEN}Added:${NC}"
        echo "$added_files" | sed 's/^/  /'
    fi

    if [ -n "$modified_files" ]; then
        echo -e "${YELLOW}Modified:${NC}"
        echo "$modified_files" | sed 's/^/  /'
    fi

    if [ -n "$deleted_files" ]; then
        echo -e "${RED}Deleted:${NC}"
        echo "$deleted_files" | sed 's/^/  /'
    fi
    echo ""
}

# Show git diff preview
show_diff_preview() {
    cd "$BACKUP_DIR"

    local num_changes=$(git diff --cached --stat | tail -1)
    log_info "Changes: $num_changes"

    # Show brief diff for each file (max 5 lines per file for readability)
    log_info "Preview of changes:"
    git diff --cached --no-color | head -100
    if [ $(git diff --cached --no-color | wc -l) -gt 100 ]; then
        echo "... (additional changes omitted for brevity)"
    fi
    echo ""
}

# Commit and push changes
commit_and_push() {
    cd "$BACKUP_DIR"

    # Add all changes
    git add -A

    # Check if there are changes to commit
    if git diff --cached --quiet; then
        log_info "No changes to commit"
        return
    fi

    # Show changed files and diff in interactive mode
    if [ "$NON_INTERACTIVE" = "false" ]; then
        show_changed_files
        show_diff_preview

        read -p "Commit these changes? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_warn "Commit cancelled by user"
            return
        fi
    else
        log_info "Non-interactive mode: committing without confirmation"
    fi

    # Commit with timestamp
    local commit_msg="Backup $(date '+%Y-%m-%d %H:%M:%S')"
    git commit -m "$commit_msg"
    log_info "Committed changes: $commit_msg"

    # Push if remote exists
    if git remote | grep -q "origin"; then
        log_info "Pushing to remote..."
        if git push origin "$(git branch --show-current)" 2>/dev/null; then
            log_info "Pushed successfully"
        else
            log_warn "Push failed - you may need to set up the remote branch"
            log_warn "Try: git push -u origin $(git branch --show-current)"
        fi
    else
        log_warn "No remote configured. Changes committed locally only."
        log_warn "Add a remote with: git remote add origin <url>"
    fi
}

# Main execution
main() {
    log_info "Starting Arch Linux configuration backup..."
    log_info "Backup directory: $BACKUP_DIR"

    create_dirs
    init_git_repo
    backup_configs
    backup_local_bin
    backup_packages
    commit_and_push

    log_info "Backup completed!"
}

main "$@"
